"""Generate sample_repo/ - a small demo codebase with deliberate crypto usage.

ALL keys and certificates produced here are THROWAWAY TEST MATERIAL generated
fresh on each run. They protect nothing. Re-run before a demo to refresh
certificate expiry dates:  python make_sample.py
"""
from __future__ import annotations

import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, rsa
from cryptography.x509.oid import NameOID

ROOT = Path(__file__).parent / "sample_repo"

FILES = {
    "README.md": """# sample_repo (ECDAT demo)
Deliberately insecure demo code generated by make_sample.py.
Every key and certificate here is throwaway test material.
""",

    # ---------------- payments (High criticality) ----------------
    "payments/rsa_keys.py": '''"""Merchant key handling for settlement files."""
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.primitives import hashes


def new_merchant_keypair():
    return rsa.generate_private_key(public_exponent=65537, key_size=2048)


def sign_settlement(key, payload: bytes) -> bytes:
    return key.sign(payload, padding.PKCS1v15(), hashes.SHA256())
''',
    "payments/PaymentSigner.java": '''package com.example.payments;

import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.Signature;
import javax.crypto.Cipher;

public class PaymentSigner {
    public KeyPair newKeyPair() throws Exception {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
        kpg.initialize(2048);
        return kpg.generateKeyPair();
    }

    public byte[] sign(KeyPair kp, byte[] msg) throws Exception {
        Signature signer = Signature.getInstance("SHA1withRSA");
        signer.initSign(kp.getPrivate());
        signer.update(msg);
        return signer.sign();
    }

    public Cipher legacyCardVault() throws Exception {
        return Cipher.getInstance("DESede/ECB/PKCS5Padding");
    }
}
''',

    # ---------------- auth (High criticality) ----------------
    "auth/token_utils.py": '''"""Session and token helpers (legacy)."""
import hashlib
import os
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes


def password_fingerprint(pw: str) -> str:
    return hashlib.md5(pw.encode()).hexdigest()


def session_id(user: str) -> str:
    return hashlib.sha1(user.encode() + os.urandom(8)).hexdigest()


def encrypt_token(token: bytes, key_128: bytes) -> bytes:
    encryptor = Cipher(algorithms.AES(key_128), modes.ECB()).encryptor()
    return encryptor.update(token.ljust(32, b"\\0")) + encryptor.finalize()
''',
    "auth/EcdsaAuth.java": '''package com.example.auth;

import java.security.KeyPairGenerator;
import java.security.Signature;
import java.security.spec.ECGenParameterSpec;
import javax.crypto.Cipher;

public class EcdsaAuth {
    public void init() throws Exception {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("EC");
        kpg.initialize(new ECGenParameterSpec("secp256r1"));
        Signature sig = Signature.getInstance("SHA256withECDSA");
        Cipher tokenCipher = Cipher.getInstance("AES");
    }
}
''',

    # ---------------- services ----------------
    "services/key_exchange.js": '''// Partner key exchange service
const crypto = require('crypto');

const ecdh = crypto.createECDH('prime256v1');
ecdh.generateKeys();

const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', { modulusLength: 2048 });

module.exports = { ecdh, publicKey, privateKey };
''',

    # ---------------- infra ----------------
    "infra/nginx.conf": '''server {
    listen 443 ssl;
    server_name pay.example.com;

    ssl_certificate     certs/server_rsa2048.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-SHA:DES-CBC3-SHA:RC4-MD5:AES256-SHA';
    ssl_prefer_server_ciphers on;
}
''',

    # ---------------- archive (Medium criticality) ----------------
    "archive/backup_crypto.py": '''"""Backup encryption - the GOOD example: AES-256-GCM + SHA-256."""
import hashlib
import os
from cryptography.hazmat.primitives.ciphers import aead


def encrypt_backup(data: bytes) -> tuple[bytes, bytes, str]:
    cipher = aead.AESGCM(aead.AESGCM.generate_key(bit_length=256))
    nonce = os.urandom(12)
    checksum = hashlib.sha256(data).hexdigest()
    return nonce, cipher.encrypt(nonce, data, None), checksum
''',

    # ---------------- pqc pilot (already post-quantum) ----------------
    "pqc/pqc_pilot.py": '''"""Pilot: post-quantum key establishment and signing via liboqs-python."""
import oqs


def pilot():
    kem = oqs.KeyEncapsulation("ML-KEM-768")
    signer = oqs.Signature("ML-DSA-65")
    return kem, signer
''',
}


def _name(cn: str):
    return x509.Name([x509.NameAttribute(NameOID.COUNTRY_NAME, "IN"),
                      x509.NameAttribute(NameOID.ORGANIZATION_NAME, "ECDAT Demo (TEST ONLY)"),
                      x509.NameAttribute(NameOID.COMMON_NAME, cn)])


def _self_signed(key, cn: str, hash_alg, valid_from: datetime, valid_to: datetime) -> bytes:
    cert = (x509.CertificateBuilder()
            .subject_name(_name(cn)).issuer_name(_name(cn))
            .public_key(key.public_key()).serial_number(x509.random_serial_number())
            .not_valid_before(valid_from).not_valid_after(valid_to)
            .sign(key, hash_alg))
    return cert.public_bytes(serialization.Encoding.PEM)


# DER-encoded OIDs (same length, so they can be swapped in place).
OID_SHA256_RSA = bytes.fromhex("2a864886f70d01010b")
OID_SHA1_RSA = bytes.fromhex("2a864886f70d010105")


def _self_signed_sha1_rsa(key, cn: str, valid_from: datetime, valid_to: datetime) -> bytes:
    """Modern OpenSSL builds refuse to SIGN certificates with SHA-1, so we build a
    SHA-256 cert, swap the signature-algorithm OID to sha1WithRSAEncryption and
    re-sign the TBS bytes with SHA-1. The result is a genuine, verifiable
    SHA-1-signed legacy certificate (exactly the kind ECDAT must flag)."""
    from cryptography.hazmat.primitives.asymmetric import padding
    cert = x509.load_pem_x509_certificate(_self_signed(key, cn, hashes.SHA256(), valid_from, valid_to))
    der = cert.public_bytes(serialization.Encoding.DER)
    tbs = cert.tbs_certificate_bytes
    new_tbs = tbs.replace(OID_SHA256_RSA, OID_SHA1_RSA)
    new_sig = key.sign(new_tbs, padding.PKCS1v15(), hashes.SHA1())
    assert len(new_sig) == len(cert.signature)
    new_der = der.replace(tbs, new_tbs).replace(OID_SHA256_RSA, OID_SHA1_RSA).replace(cert.signature, new_sig)
    new_cert = x509.load_der_x509_certificate(new_der)
    key.public_key().verify(new_cert.signature, new_cert.tbs_certificate_bytes,
                            padding.PKCS1v15(), hashes.SHA1())        # self-check
    return new_cert.public_bytes(serialization.Encoding.PEM)


def main() -> None:
    if ROOT.exists():
        shutil.rmtree(ROOT)
    for rel, content in FILES.items():
        p = ROOT / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8", newline="\n")

    # Hard-coded PEM private key (throwaway, generated now).
    dev_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    pem = dev_key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                serialization.NoEncryption()).decode()
    (ROOT / "auth/dev_keys.py").write_text(
        "# THROWAWAY TEST KEY generated by make_sample.py - protects nothing.\n"
        f'DEV_SIGNING_KEY = """{pem}"""\n', encoding="utf-8", newline="\n")

    # Three X.509 certificates.
    now = datetime.now(timezone.utc)
    certs = ROOT / "infra/certs"
    certs.mkdir(parents=True, exist_ok=True)
    (certs / "server_rsa2048.pem").write_bytes(_self_signed(
        rsa.generate_private_key(public_exponent=65537, key_size=2048), "pay.example.com",
        hashes.SHA256(), now - timedelta(days=30), now + timedelta(days=365)))
    (certs / "api_ecdsa_p256.pem").write_bytes(_self_signed(
        ec.generate_private_key(ec.SECP256R1()), "api.example.com",
        hashes.SHA256(), now - timedelta(days=30), now + timedelta(days=365)))
    (certs / "legacy_rsa1024_sha1.pem").write_bytes(_self_signed_sha1_rsa(
        rsa.generate_private_key(public_exponent=65537, key_size=1024), "legacy.example.com",
        now - timedelta(days=700), now + timedelta(days=60)))   # near expiry

    # A binary file, to show the scanner skips it.
    (ROOT / "archive/blob.bin").write_bytes(b"\x00\x01ECDAT-binary\x00" * 16)
    print(f"sample repo written to {ROOT}")


if __name__ == "__main__":
    main()
